language: node_js
node_js:
  - '9'
deploy:
  script: 'cp .npmrc.template $HOME/.npmrc && npm publish'
  provider: script
  on:
    tags: true
notifications:
  email:
    recipients:
      - msroed@gmail.com
    on_success: change
    on_failure: always
